version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - mongoDBURI=mongodb://mongodb:27017/form-management
    depends_on:
      - mongodb
    volumes:
      - ./:/usr/src/app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: